# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-dms-replication-instance
  description: This component provisions DMS replication instances
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component





